#!/usr/bin/env bash
# loops from 1 to 20

MYCOUNT=1
while [ $MYCOUNT -le 20 ]
do
	echo "$MYCOUNT"
	case $MYCOUNT in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
        (( MYCOUNT++ ))
done
